version: "3"
services:
  app:
    restart: always
    container_name: frontend_studen_market_place
    hostname: frontend_studen_market_place
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules


